### ISSUE TITLE
How to fetch artwork from AppleTV using the library ?

### ISSUE THREAD

**Issue by aishwaryec** [evandcoleman/node-appletv#32]
I am wondering how we can fetch the artwork updates from the appleTV. Do we have to subscribe to "playbackQueue" event ? What format the artwork will be in ?

**Comment by evandcoleman** [comment]
This is not currently possible using this library. I will add it to my todo list though!

**Comment by mschwartz** [comment]
Instead of opening a new issue...

There is a pyatv (python) repository on GitHub that has some additional functionality.

Something I find missing is artist and show and other information.

The best I get from this library is something like "Netflix" and "S1E1 Pilot" but no "Grey's Anatomy" or other info (actors?  what else is there?)

I've seen this information displayed in other apps on my phone or iPad.  I mentioned pyatv in case you can inspect their code to see what to do for yours.

Thanks for this!
